--
-- 독스링고 Supabase 스키마 (실행 가이드)
--
-- Supabase SQL Editor는 파일 include를 지원하지 않으므로
-- 역할별 SQL 파일을 아래 순서대로 각각 실행하세요.
--
-- =============================================================
-- 신규 설치 (전체)
-- =============================================================
-- 1. supabase/schemas/01-auth.sql
-- 2. supabase/schemas/02-profile.sql
-- 3. supabase/schemas/03-translation.sql
-- 4. supabase/schemas/04-bookmark.sql
-- 5. supabase/schemas/05-triggers.sql
-- 6. supabase/schemas/06-storage.sql
-- 7. supabase/schemas/07-rls-grants.sql
--
-- 설치 후 필수 설정:
-- Project Settings > Data API > Exposed schemas 에 next_auth 추가
-- =============================================================
-- 역할별 파일 설명
-- =============================================================
-- 01-auth.sql        : SNS 로그인 (next_auth)
-- 02-profile.sql     : 프로필, AI 설정, 프로필 변경 히스토리
-- 03-translation.sql : 문서, 번역 히스토리
-- 04-bookmark.sql    : 북마크 폴더, 북마크
-- 05-triggers.sql    : 회원가입/프로필 수정 트리거
-- 06-storage.sql     : 프로필 이미지 Storage
-- 07-rls-grants.sql  : 테이블 권한, RLS 정책
